# This is a basic workflow to help you get started with Actions

name: Build dataset

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Runs a set of commands using the runners shell
      - name: Install and run lean-training-data
        run: |
          git clone https://github.com/semorrison/lean-training-data.git
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y
          cd ./lean-training-data/
          export PATH=$PATH:~/.elan/bin
          lake exe cache get
          timeout 30 ./scripts/training_data.sh || [ $? -eq 124 ] && exit 0 || exit $?
